@BaseUrl = https://localhost:5050
@productId = 01987aa3-db9f-4296-b1d3-9d9cc553812e
@productCategory = gadgets

### Create product
POST {{BaseUrl}}/products
Content-Type: application/json

{
  "name": "",
  "description": "This is a great product.",
  "price": 99.99,
  "category": [
    "electronics",
    "gadgets"
  ],
  "imageFile": "example-image.png"
}

### Get all products
GET {{BaseUrl}}/products?pageNumber=1&pageSize=1
Accept: application/json

### Get product by ID
GET {{BaseUrl}}/products/{{productId}}
Accept: application/json

### Get products by category
GET {{BaseUrl}}/products/category/{{productCategory}}
Accept: application/json

### Update product
PUT {{BaseUrl}}/products
Content-Type: application/json

{
  "id": "{{productId}}",
  "name": "Updated Example Product Name",
  "description": "This product has been updated.",
  "price": 129.99,
  "category": [
    "electronics",
    "updated-gadgets"
  ],
  "imageFile": "updated-image.png"
}

### Delete a product
DELETE {{BaseUrl}}/products/{{productId}}